### ISSUE TITLE
Add more frameworks

### ISSUE THREAD

**Issue by diptangsu** [diptangsu/awesome-starter-templates#1]
Make sure you read the README and follow all the guidelines. Please create/fill up the necessary readme files inside the framework folders.

**Comment by gitaalekhyapaul** [comment]
I would like to Make a TypeScript as well as JavaScript Node.js Example. Can you also add Typescript to the list?

**Comment by diptangsu** [comment]
@gitaalekhyapaul The point of this is, I don't know all frameworks and I don't even know what frameworks to include in this list/repo. I simply added a few of them in python as a starting point to set the structure of the repository as I felt right.

Feel free to add your own language, dir and readme based on what you want to contribute. And update the main readme file based on what you're adding.

So, I could add ts to the list, but you can too!

**Comment by abhinav72610** [comment]
i would like to contribute in the flask section as in i can add basic crud app and basic crud api if you want i would like to move forward ..

**Comment by diptangsu** [comment]
Add anything guys. It's a free world!
Just remember, if it's python, I won't merge if your code does not follow proper standards.

**Comment by saiteja310** [comment]
@diptangsu I would like to contribute towards C# section. 
Do I need to open up an issue for C# separately and raise my pr against it or raising one against this issue would suffice?

**Comment by diptangsu** [comment]
@saiteja310 If you want a new issue you can just go ahead and create one. If you raise your PR against this one, that is also fine.

I'm not going to assign this issue to any particular person, this is for everyone to understand this requirement.

It's up to you basically.

**Comment by NAMAN9JAIN** [comment]
@diptangsu I would like to contribute to Django Framework. I recently started learning and also have started to work on Blog clone project. Can I?

**Comment by abhishek7553** [comment]
can i add data structures to your repo?
