### ISSUE TITLE
Add readme files for each language directories

### ISSUE THREAD

**Issue by diptangsu** [diptangsu/awesome-starter-templates#2]
Add details about each language in the readme files present within each language directory.

**Comment by AsaoluElijah** [comment]
Hi, I'll love to work on this.

**Comment by Hinal-Srivastava** [comment]
Will Contribute to this!
#HacktoberFest

**Comment by uditmore99** [comment]
I'd like to work on this !
#HacktoberFest

**Comment by sk1122** [comment]
I'll help in Django Crud API

**Comment by Niteshkumarji** [comment]
We will work hard and will make #hacktoberfest  more awesome

**Comment by diptangsu** [comment]
Awesome!

**Comment by NAMAN9JAIN** [comment]
I really would like to work and contribute on this. 
#makehacktoberfestawesome

**Comment by Niteshkumarji** [comment]
Thank you

**Comment by Echelon101** [comment]
Hi, 
I would like to help with symfony hello world app.

**Comment by diptangsu** [comment]
@Echelon101 Sure!

Guys you don't have to comment here what you want to add to this repo, you can just go ahead and fork it and add your changes!

It's not like I'll ask you not to contribute anything unless the code is already present here.

**Comment by abhishek7553** [comment]
me too wanna contribute
